# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.akm.root] run return 0
execute unless entity @s[tag=!aj.akm.animation.equip.playing,tag=!aj.akm.animation.walk.playing,tag=!aj.akm.animation.shoot.playing,tag=!aj.akm.animation.reload.playing,tag=!aj.akm.animation.reload2.playing,tag=!aj.akm.animation.run.playing,tag=!aj.akm.animation.use.playing,tag=!aj.akm.animation.wall.playing,tag=!aj.akm.animation.empty.playing] run function animated_java:akm/root/tick_animations
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:akm/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~