# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.akm.root] run return 0
execute if entity @s[tag=aj.akm.animation.equip.playing] run function animated_java:akm/animations/equip/zzz/on_tick
execute if entity @s[tag=aj.akm.animation.shoot.playing] run function animated_java:akm/animations/shoot/zzz/on_tick
execute if entity @s[tag=aj.akm.animation.reload.playing] run function animated_java:akm/animations/reload/zzz/on_tick
execute if entity @s[tag=aj.akm.animation.run.playing] run function animated_java:akm/animations/run/zzz/on_tick
execute if entity @s[tag=aj.akm.animation.use.playing] run function animated_java:akm/animations/use/zzz/on_tick
execute if entity @s[tag=aj.akm.animation.wall.playing] run function animated_java:akm/animations/wall/zzz/on_tick
execute if entity @s[tag=aj.akm.animation.empty.playing] run function animated_java:akm/animations/empty/zzz/on_tick
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:akm/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~