# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
gamemode spectator @p
function animated_java:player/as_camera {name:"camera", "command":"spectate @s @p"}
function animated_java:player/as_camera {name:"camera", "command":"data modify entity @s teleport_duration set value 2"}
execute as @a at @s run playsound deadism:ambience.wakeup