# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
gamemode adventure @p
function animated_java:player/as_camera {name:"camera", "command":"execute positioned ~ ~-1 ~ run tp @p ~ ~ ~"}