# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set #aj.check aj.i 1
$execute as $(uuid) run return run $(command)
tellraw @a [{color:'red',text:''},{color:'gray',text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:'dark_gray',italic:true,text:'\n (animated_java:glock)'},'\n → ᴇʀʀᴏʀ: ',{color:'red',underlined:true,text:'Node Not Found'},'\n\n Node ',{color:'aqua',nbt:'args.name',storage:'animated_java:temp'},' does not exist!\n Please ensure that its name is spelled correctly.\n']