# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:glock rig_hash set value '243321717b1bd303532d86c505cf7d4e7dc88b1aaa550ca51ddb45a443da3415'
scoreboard objectives add aj.equip.frame dummy
scoreboard objectives add aj.shoot.frame dummy
scoreboard objectives add aj.shoot_final.frame dummy
scoreboard objectives add aj.reload_mid.frame dummy
scoreboard objectives add aj.reload_empty.frame dummy
scoreboard objectives add aj.sprint.frame dummy
scoreboard objectives add aj.use.frame dummy