# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:glock rig_hash set value 'fd8e4c3b148662178c8eeb08e2732cd80cef61afd683911189d7c885c0ce939a'
scoreboard objectives add aj.equip.frame dummy
scoreboard objectives add aj.shoot.frame dummy
scoreboard objectives add aj.shoot_final.frame dummy
scoreboard objectives add aj.reload_mid.frame dummy
scoreboard objectives add aj.reload_empty.frame dummy
scoreboard objectives add aj.sprint.frame dummy
scoreboard objectives add aj.use.frame dummy