# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(magazine) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(chamber) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(akm1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(right_arm) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(magazine2) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(forearm) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i