# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.ceiling_fan.root] run return 0
execute if entity @s[tag=aj.ceiling_fan.animation.move.playing] run function animated_java:ceiling_fan/animations/move/zzz/on_tick
execute on passengers run rotate @s ~ ~