# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
playsound deadism:sfx.weapons.akm.shoot master @a ~ ~ ~ 1 1
data modify entity @s item set value {id:"sea_lantern",count:1}