# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify entity $(shotgun_shell) interpolation_duration set value 1
$data modify entity $(clock) interpolation_duration set value 1
$data modify entity $(barrel1) interpolation_duration set value 1
$data modify entity $(trigger) interpolation_duration set value 1
$data modify entity $(trigger_part) interpolation_duration set value 1
$data modify entity $(chrome_shotgun) interpolation_duration set value 1
$data modify entity $(shotgun_shell1) interpolation_duration set value 1
$data modify entity $(right_arm) interpolation_duration set value 1
$data modify entity $(left_arm) interpolation_duration set value 1