# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s add hands_weapons.model
tag @s add new
execute as @e[tag=aj.hands_weapons_fireextinguisher.root,distance=..1] run data modify entity @s view_range set value 0.005
function animated_java:hands_weapons_fireextinguisher/animations/equip/play