# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data merge value {"cameras":{"camera":{"px":0,"py":0.03125,"pz":0,"ry":0,"rx":-90}},"locators":{}}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:player/animations/wakeup/zzz/frames/0_root_function