# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
gamemode spectator @p
function animated_java:player/as_camera {name:"camera", "command":"spectate @s @p"}
execute as @a at @s run playsound deadism:ambience.wakeup