# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shotgun_shell) {transformation: [0f,0f,0f,-0.1563f,0f,0f,0f,-0.2156f,0f,0f,0f,0.2156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_clock) {transformation: [-1f,0f,0f,-0.1094f,0f,1f,0f,-0.3281f,0f,0f,-1f,0.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_barrel1) {transformation: [-1f,0f,0f,-0.1094f,0f,1f,0f,-0.2969f,0f,0f,-1f,0.3906f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_trigger) {transformation: [-1f,0f,0f,-0.1406f,0f,1f,0f,-0.3134f,0f,0f,-1f,0.2149f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_trigger_part) {transformation: [-1f,0f,0f,-0.1406f,0f,1f,0f,-0.3219f,0f,0f,-1f,0.2344f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_chrome_shotgun) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,-0.2813f,0f,0f,-1f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shotgun_shell1) {transformation: [0f,0f,0f,-0.1123f,0f,0f,0f,-0.2781f,0f,0f,0f,0.1733f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-0.9914f,-0.1305f,0f,-0.2187f,0f,0f,-1f,-0.3125f,0.1305f,-0.9914f,0f,-0.1562f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-0.839f,0.4982f,-0.2188f,-0.0156f,0.2995f,0.0871f,-0.9501f,-0.3125f,-0.4542f,-0.8627f,-0.2223f,1.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"barrel":{"px":-0.1406250000000001,"py":-0.24687500000000007,"pz":0.90625,"ry":0,"rx":0}}}