# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shotgun_shell) {transformation: [0f,0f,0f,-0.2813f,0f,0f,0f,-0.3375f,0f,0f,0f,0.2437f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_clock) {transformation: [-1f,0f,0f,-0.1875f,0f,1f,0f,-0.5625f,0f,0f,-1f,1.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_barrel) {transformation: [-1f,0f,0f,-0.1875f,0f,1f,0f,-0.5f,0f,0f,-1f,0.5938f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_trigger) {transformation: [-1f,0f,0f,-0.25f,0f,1f,0f,-0.5331f,0f,0f,-1f,0.2423f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_trigger_part) {transformation: [-1f,0f,0f,-0.25f,0f,1f,0f,-0.55f,0f,0f,-1f,0.2813f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_chrome_shotgun) {transformation: [-1.0243f,0f,0f,-0.2188f,0f,1.0243f,0f,-0.4688f,0f,0f,-1.0243f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-0.9914f,-0.1305f,0f,-0.4062f,0f,0f,-1f,-0.5312f,0.1305f,-0.9914f,0f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-0.8565f,0.5085f,-0.2234f,0.1875f,0.3058f,0.0889f,-0.9699f,-0.5313f,-0.4637f,-0.8807f,-0.227f,0.7188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}