# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
summon minecraft:item_display ^-0.20625 ^-1.15625 ^0.475 {Tags:["aj.global.bone.glock.child","aj.global.bone.glock.child.locator","aj.global.bone.glock.decendant","aj.global.bone.glock.decendant.locator","aj.global.bone.glock.tree","aj.global.bone.right_arm.decendant","aj.global.bone.right_arm.decendant.locator","aj.global.bone.right_arm.tree","aj.global.bone.torso.decendant","aj.global.bone.torso.decendant.locator","aj.global.bone.torso.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.barrel1","aj.glock.bone.glock.child","aj.glock.bone.glock.child.locator","aj.glock.bone.glock.decendant","aj.glock.bone.glock.decendant.locator","aj.glock.bone.glock.tree","aj.glock.bone.right_arm.decendant","aj.glock.bone.right_arm.decendant.locator","aj.glock.bone.right_arm.tree","aj.glock.bone.torso.decendant","aj.glock.bone.torso.decendant.locator","aj.glock.bone.torso.tree","aj.glock.entity","aj.glock.locator","aj.glock.locator.barrel1","aj.glock.node","aj.glock.node.barrel1","aj.new"]}
execute as @n[ type=minecraft:item_display, tag=aj.glock.locator.barrel1, tag=aj.new, distance=..2 ] run function animated_java:glock/zzz/summon/as_data_entity/as_locator/barrel1
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.locator_barrel1 set from storage animated_java:gu out
data modify entity @s data.locators.barrel1.uuid set from storage animated_java:gu out
summon minecraft:text_display ^-0.0875 ^-0.88125 ^0.44375 {Tags:["aj.global.bone.glock.child","aj.global.bone.glock.child.locator","aj.global.bone.glock.decendant","aj.global.bone.glock.decendant.locator","aj.global.bone.glock.tree","aj.global.bone.right_arm.decendant","aj.global.bone.right_arm.decendant.locator","aj.global.bone.right_arm.tree","aj.global.bone.torso.decendant","aj.global.bone.torso.decendant.locator","aj.global.bone.torso.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.ammo_display","aj.glock.bone.glock.child","aj.glock.bone.glock.child.locator","aj.glock.bone.glock.decendant","aj.glock.bone.glock.decendant.locator","aj.glock.bone.glock.tree","aj.glock.bone.right_arm.decendant","aj.glock.bone.right_arm.decendant.locator","aj.glock.bone.right_arm.tree","aj.glock.bone.torso.decendant","aj.glock.bone.torso.decendant.locator","aj.glock.bone.torso.tree","aj.glock.entity","aj.glock.locator","aj.glock.locator.ammo_display","aj.glock.node","aj.glock.node.ammo_display","aj.new"]}
execute as @n[ type=minecraft:text_display, tag=aj.glock.locator.ammo_display, tag=aj.new, distance=..2 ] run function animated_java:glock/zzz/summon/as_data_entity/as_locator/ammo_display
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.locator_ammo_display set from storage animated_java:gu out
data modify entity @s data.locators.ammo_display.uuid set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.glock.node.slide] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_slide set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.glock.node.barrel] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_barrel set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.glock.node.magazine] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_magazine set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.glock.node.grip] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_grip set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.glock.node.trigger] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_trigger set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.glock.node.trigger_gaurd] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_trigger_gaurd set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.glock.node.right_arm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_arm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.glock.node.magazine1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_magazine1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.glock.node.left_arm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_arm set from storage animated_java:gu out