# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @p add deadism.weapon.cooldown
execute as @p at @s run function deadism:zprivate/weapons/pistols/glock/recoil/init {x_min:-25,x_max:25,y_min:-84,y_max:-18}