# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @p add deadism.weapon.cooldown
execute as @p at @s run function deadism:zprivate/weapons/pistols/glock/recoil/init {x_min:-250,x_max:250,y_min:-840,y_max:-180}