# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @p remove deadism.weapon.cooldown
playsound deadism:sfx.weapons.chrome_shotgun.deploy master @a ~ ~ ~ 1 1.3