# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on vehicle run tag @s remove deadism.weapon.cooldown
execute on vehicle run tag @s remove deadism.weapon.reloading
playsound deadism:sfx.weapons.chrome_shotgun.deploy master @a ~ ~ ~ 1 1.3