# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shotgun_shell) {transformation: [0f,0f,0f,-0.2188f,0f,0f,0f,-0.6844f,0f,0f,0f,0.3719f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_clock) {transformation: [-1f,0f,0f,-0.1719f,0f,1f,0f,-0.7969f,0f,0f,-1f,0.7813f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_barrel1) {transformation: [-1f,0f,0f,-0.1719f,0f,1f,0f,-0.7656f,0f,0f,-1f,0.5469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_trigger) {transformation: [-1f,0f,0f,-0.2031f,0f,1f,0f,-0.7822f,0f,0f,-1f,0.3711f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_trigger_part) {transformation: [-1f,0f,0f,-0.2031f,0f,1f,0f,-0.7906f,0f,0f,-1f,0.3906f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_chrome_shotgun) {transformation: [-1f,0f,0f,-0.1875f,0f,1f,0f,-0.75f,0f,0f,-1f,0.4063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shotgun_shell1) {transformation: [0f,0f,0f,-0.1748f,0f,0f,0f,-0.7469f,0f,0f,0f,0.3296f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-0.9914f,-0.1305f,0f,-0.2812f,0f,0f,-1f,-0.7812f,0.1305f,-0.9914f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-0.839f,0.4982f,-0.2188f,-0.0156f,0.2995f,0.0871f,-0.9501f,-0.7813f,-0.4542f,-0.8627f,-0.2223f,0.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"barrel":{"px":-0.20312500000000014,"py":-0.7156250000000001,"pz":1.0625,"ry":0,"rx":0}}}