# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shotgun_shell) {transformation: [0f,0f,0f,-0.2188f,0f,0f,0f,-0.3406f,0f,0f,0f,0.2781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_clock) {transformation: [-1f,0f,0f,-0.1719f,0f,1f,0f,-0.4531f,0f,0f,-1f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_barrel1) {transformation: [-1f,0f,0f,-0.1719f,0f,1f,0f,-0.4219f,0f,0f,-1f,0.4531f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_trigger) {transformation: [-1f,0f,0f,-0.2031f,0f,1f,0f,-0.4384f,0f,0f,-1f,0.2774f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_trigger_part) {transformation: [-1f,0f,0f,-0.2031f,0f,1f,0f,-0.4469f,0f,0f,-1f,0.2969f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_chrome_shotgun) {transformation: [-1f,0f,0f,-0.1875f,0f,1f,0f,-0.4063f,0f,0f,-1f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shotgun_shell1) {transformation: [0f,0f,0f,-0.1748f,0f,0f,0f,-0.4031f,0f,0f,0f,0.2358f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-0.9914f,-0.1305f,0f,-0.2812f,0f,0f,-1f,-0.4375f,0.1305f,-0.9914f,0f,-0.0937f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-0.839f,0.4982f,-0.2188f,-0.0156f,0.2995f,0.0871f,-0.9501f,-0.4375f,-0.4542f,-0.8627f,-0.2223f,0.5313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"barrel":{"px":-0.20312500000000014,"py":-0.37187500000000007,"pz":0.96875,"ry":0,"rx":0}}}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:chrome_shotgun/animations/equip/zzz/frames/23_root_function