# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shotgun_shell) {transformation: [0f,0f,0f,-0.2188f,0f,0f,0f,-0.5594f,0f,0f,0f,0.5594f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_clock) {transformation: [-1f,0f,0f,-0.1719f,0f,1f,0f,-0.6719f,0f,0f,-1f,0.9688f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_barrel1) {transformation: [-1f,0f,0f,-0.1719f,0f,1f,0f,-0.6406f,0f,0f,-1f,0.7344f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_trigger) {transformation: [-1f,0f,0f,-0.2031f,0f,1f,0f,-0.6572f,0f,0f,-1f,0.5586f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_trigger_part) {transformation: [-1f,0f,0f,-0.2031f,0f,1f,0f,-0.6656f,0f,0f,-1f,0.5781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_chrome_shotgun) {transformation: [-1f,0f,0f,-0.1875f,0f,1f,0f,-0.625f,0f,0f,-1f,0.5938f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shotgun_shell1) {transformation: [0f,0f,0f,-0.1748f,0f,0f,0f,-0.6219f,0f,0f,0f,0.5171f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-0.9914f,-0.1305f,0f,-0.2812f,0f,0f,-1f,-0.6562f,0.1305f,-0.9914f,0f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-0.839f,0.4982f,-0.2188f,-0.0156f,0.2995f,0.0871f,-0.9501f,-0.6563f,-0.4542f,-0.8627f,-0.2223f,0.8125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"barrel":{"px":-0.20312500000000017,"py":-0.5906250000000001,"pz":1.25,"ry":0,"rx":0}}}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:chrome_shotgun/animations/equip/zzz/frames/23_root_function