# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_magazine1) {transformation: [0f,0f,0f,-0.1717f,0f,0f,0f,-0.403f,0f,0f,0f,0.46f,0f,0f,0f,1f],start_interpolation: -1,interpolation_duration: 0}
$data merge entity $(bone_chamber1) {transformation: [0f,0f,0f,-0.1717f,0f,0f,0f,-0.403f,0f,0f,0f,0.46f,0f,0f,0f,1f],start_interpolation: -1,interpolation_duration: 0}
$data merge entity $(bone_akm3) {transformation: [0f,0f,0f,-0.1717f,0f,0f,0f,-0.403f,0f,0f,0f,0.46f,0f,0f,0f,1f],start_interpolation: -1,interpolation_duration: 0}
data modify entity @s data merge value {"cameras":{},"locators":{"akm2":{"px":-0.171719579625429,"py":-0.40298792384375637,"pz":0.46001167272765875,"ry":353.1533319343765,"rx":-3.8659786993221745}}}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:akm/animations/reload2/zzz/frames/85_root_function