# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify entity $(shotgun_shell) start_interpolation set value -1
$data modify entity $(clock) start_interpolation set value -1
$data modify entity $(barrel1) start_interpolation set value -1
$data modify entity $(trigger) start_interpolation set value -1
$data modify entity $(trigger_part) start_interpolation set value -1
$data modify entity $(chrome_shotgun) start_interpolation set value -1
$data modify entity $(shotgun_shell1) start_interpolation set value -1
$data modify entity $(right_arm) start_interpolation set value -1
$data modify entity $(left_arm) start_interpolation set value -1