# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shotgun_shell) {transformation: [-1f,0f,0f,-0.2187f,0f,0f,1f,-1.1219f,0f,1f,0f,0.1281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_clock) {transformation: [-1f,0f,0f,-0.1719f,0f,0f,1f,-1.5312f,0f,1f,0f,0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_barrel1) {transformation: [-1f,0f,0f,-0.1719f,0f,0f,1f,-1.2969f,0f,1f,0f,0.0469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_trigger) {transformation: [-1f,0f,0f,-0.2031f,0f,0f,1f,-1.1211f,0f,1f,0f,0.0303f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_trigger_part) {transformation: [-1f,0f,0f,-0.2031f,0f,0f,1f,-1.1406f,0f,1f,0f,0.0219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_chrome_shotgun) {transformation: [-1f,0f,0f,-0.1875f,0f,0f,1f,-1.1562f,0f,1f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shotgun_shell1) {transformation: [-0.9914f,0.1305f,0f,-0.1748f,-0.1305f,-0.9914f,0f,-1.0796f,0f,0f,1f,0.0656f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-0.9914f,-0.1305f,0f,-0.2812f,-0.1305f,0.9914f,0f,-0.75f,0f,0f,-1f,0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-1f,0f,0f,0.1094f,0f,1f,0f,-0.75f,0f,0f,-1f,0.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"barrel":{"px":-0.203125,"py":-1.8125,"pz":0.09687500000000017,"ry":0,"rx":90}}}