# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shotgun_shell) {transformation: [-1f,0f,0f,-0.2188f,0f,0f,1f,-0.8406f,0f,1f,0f,0.3156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_clock) {transformation: [-1f,0f,0f,-0.1719f,0f,0f,1f,-1.25f,0f,1f,0f,0.2031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_barrel1) {transformation: [-1f,0f,0f,-0.1719f,0f,0f,1f,-1.0156f,0f,1f,0f,0.2344f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_trigger) {transformation: [-1f,0f,0f,-0.2031f,0f,0f,1f,-0.8399f,0f,1f,0f,0.2178f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_trigger_part) {transformation: [-1f,0f,0f,-0.2031f,0f,0f,1f,-0.8594f,0f,1f,0f,0.2094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_chrome_shotgun) {transformation: [-1f,0f,0f,-0.1875f,0f,0f,1f,-0.875f,0f,1f,0f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shotgun_shell1) {transformation: [-0.9914f,0.1305f,0f,-0.1748f,-0.1305f,-0.9914f,0f,-0.7983f,0f,0f,1f,0.2531f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-0.9914f,-0.1305f,0f,-0.2812f,-0.1305f,0.9914f,0f,-0.4687f,0f,0f,-1f,0.2188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-1f,0f,0f,0.1094f,0f,1f,0f,-0.4687f,0f,0f,-1f,0.2188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"barrel":{"px":-0.20312500000000003,"py":-1.53125,"pz":0.2843750000000002,"ry":0,"rx":90}}}