# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(shotgun_shell) { transformation: [-1f,0f,0f,-0.2187f,0f,0f,1f,-1.0594f,0f,1f,0f,0.2531f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(clock) { transformation: [-1f,0f,0f,-0.1719f,0f,0f,1f,-1.4687f,0f,1f,0f,0.1406f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(barrel1) { transformation: [-1f,0f,0f,-0.1719f,0f,0f,1f,-1.2344f,0f,1f,0f,0.1719f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(trigger) { transformation: [-1f,0f,0f,-0.2031f,0f,0f,1f,-1.0586f,0f,1f,0f,0.1553f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(trigger_part) { transformation: [-1f,0f,0f,-0.2031f,0f,0f,1f,-1.0781f,0f,1f,0f,0.1469f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(chrome_shotgun) { transformation: [-1f,0f,0f,-0.1875f,0f,0f,1f,-1.0937f,0f,1f,0f,0.1875f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(shotgun_shell1) { transformation: [-0.9914f,0.1305f,0f,-0.1748f,-0.1305f,-0.9914f,0f,-1.0171f,0f,0f,1f,0.1906f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(right_arm) { transformation: [-0.9914f,-0.1305f,0f,-0.2812f,-0.1305f,0.9914f,0f,-0.6875f,0f,0f,-1f,0.1563f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(left_arm) { transformation: [-1f,0f,0f,0.1094f,0f,1f,0f,-0.6875f,0f,0f,-1f,0.1563f,0f,0f,0f,1f], start_interpolation: 0 }