# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:fire_extinguisher rig_hash set value 'db715da57cb778313a8807d8da7f3fba33c98fc899c37c60a8f1b4dff6ca2ee5'
scoreboard objectives add aj.equip.frame dummy
scoreboard objectives add aj.hit.frame dummy