# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @p add deadism.weapon.cooldown
tag @p remove deadism.weapon.reloading
tag @p remove deadism.weapon.recoil.fixRotation
playsound deadism:sfx.weapons.chrome_shotgun.shoot master @a ~ ~ ~ 1 1