# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(muzzleflash) ~ ~ ~ ~ ~
$execute as $(muzzleflash) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(slide) ~ ~ ~ ~ ~
$execute as $(slide) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(barrel) ~ ~ ~ ~ ~
$execute as $(barrel) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(magazine) ~ ~ ~ ~ ~
$execute as $(magazine) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(grip) ~ ~ ~ ~ ~
$execute as $(grip) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(trigger) ~ ~ ~ ~ ~
$execute as $(trigger) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(trigger_gaurd) ~ ~ ~ ~ ~
$execute as $(trigger_gaurd) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(right_arm) ~ ~ ~ ~ ~
$execute as $(right_arm) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(magazine1) ~ ~ ~ ~ ~
$execute as $(magazine1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(left_arm) ~ ~ ~ ~ ~
$execute as $(left_arm) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1