# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.zombie.root] run return 0
execute if entity @s[tag=aj.zombie.animation.idle1.playing] run function animated_java:zombie/animations/idle1/zzz/on_tick
execute if entity @s[tag=aj.zombie.animation.walk1.playing] run function animated_java:zombie/animations/walk1/zzz/on_tick
execute if entity @s[tag=aj.zombie.animation.hit1.playing] run function animated_java:zombie/animations/hit1/zzz/on_tick
execute if entity @s[tag=aj.zombie.animation.death1.playing] run function animated_java:zombie/animations/death1/zzz/on_tick
execute if entity @s[tag=aj.zombie.animation.stun1.playing] run function animated_java:zombie/animations/stun1/zzz/on_tick
execute on passengers run rotate @s ~ ~