# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:zombie/animations/walk1/zzz/apply_frame {frame: 20}
scoreboard players add @s aj.walk1.frame 1