# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(muzzleflash) { transformation: [-0.999f,-0.0436f,0f,-0.2031f,-0.0436f,0.999f,0f,-0.7078f,0f,0f,-1f,0.4f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(slide) { transformation: [-1f,0f,0f,-0.1844f,0f,0f,1f,-0.875f,0f,1f,0f,0.3297f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(barrel) { transformation: [-1f,0f,0f,-0.075f,0f,0f,1f,-0.875f,0f,1f,0f,0.2488f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(magazine) { transformation: [-1f,0f,0f,-0.1844f,0f,0f,1f,-0.678f,0f,1f,0f,0.1962f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(grip) { transformation: [-1f,0f,0f,-0.1844f,0f,0f,1f,-0.678f,0f,1f,0f,0.1962f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(trigger) { transformation: [-1f,0f,0f,-0.1844f,0f,0f,1f,-0.7087f,0f,1f,0f,0.2006f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(trigger_gaurd) { transformation: [-1f,0f,0f,-0.1844f,0f,0f,1f,-0.7411f,0f,1f,0f,0.2295f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(right_arm) { transformation: [-1f,0f,0f,-0.2188f,0f,1f,0f,-0.35f,0f,0f,-1f,0.175f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(magazine1) { transformation: [-1f,0f,0f,0.1719f,0f,-0.3827f,0.9239f,-0.735f,0f,0.9239f,0.3827f,0.2905f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(left_arm) { transformation: [-1f,0f,0f,0.1719f,0f,1f,0f,-0.35f,0f,0f,-1f,0.175f,0f,0f,0f,1f], start_interpolation: 0 }