# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:chrome_shotgun/animations/reload_load1/zzz/apply_frame {frame: 10}
scoreboard players add @s aj.reload_load1.frame 1