# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chrome_shotgun.node.shotgun_shell] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_shotgun_shell set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chrome_shotgun.node.clock] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_clock set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chrome_shotgun.node.barrel1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_barrel1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chrome_shotgun.node.trigger] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_trigger set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chrome_shotgun.node.trigger_part] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_trigger_part set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chrome_shotgun.node.chrome_shotgun] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_chrome_shotgun set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chrome_shotgun.node.shotgun_shell1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_shotgun_shell1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chrome_shotgun.node.right_arm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_arm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.chrome_shotgun.node.left_arm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_arm set from storage animated_java:gu out