# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.player.root] run return 0
execute if entity @s[tag=aj.player.animation.wakeup.playing] run function animated_java:player/animations/wakeup/zzz/on_tick
execute if entity @s[tag=aj.player.animation.s1.playing] run function animated_java:player/animations/s1/zzz/on_tick
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:player/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~