# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(muzzleflash) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(slide) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(barrel) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(magazine) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(grip) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(trigger) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(trigger_gaurd) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(right_arm) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(magazine1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(left_arm) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i