# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify entity $(muzzleflash) start_interpolation set value -1
$data modify entity $(slide) start_interpolation set value -1
$data modify entity $(barrel) start_interpolation set value -1
$data modify entity $(magazine) start_interpolation set value -1
$data modify entity $(grip) start_interpolation set value -1
$data modify entity $(trigger) start_interpolation set value -1
$data modify entity $(trigger_gaurd) start_interpolation set value -1
$data modify entity $(right_arm) start_interpolation set value -1
$data modify entity $(magazine1) start_interpolation set value -1
$data modify entity $(left_arm) start_interpolation set value -1