# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s background set value 0
data modify entity @s billboard set value "center"
data modify entity @s see_through set value true
data modify entity @s transformation.scale set value [0.1f,0.1f,0.1f]
data modify entity @s view_range set value 0f
data modify entity @s teleport_duration set value 2
function animated_java:global/util/get_entity_stack_uuids