# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @p remove deadism.weapon.cooldown
tag @p add deadism.weapon.reloading
execute as @p run title @s actionbar [{"score":{name:"@s", "objective":"deadism.weapon.AMMO.IN_GUN"}}, "/", {"score":{"name":"@s", objective:"deadism.weapon.AMMO.RELOADABLE_AMOUNT"}}]