# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:ceiling_fan rig_hash set value '54193fa10b43428ccf72db18bfad8bed24ad9d3f838bd500314fbcd83e47df82'
scoreboard objectives add aj.move.frame dummy