# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_muzzleflash) {transformation: [-0.999f,-0.0436f,0f,-0.2031f,-0.0436f,0.999f,0f,-0.7703f,0f,0f,-1f,0.4f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_slide) {transformation: [-1f,0f,0f,-0.1844f,0f,0f,1f,-0.9375f,0f,1f,0f,0.3297f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_barrel) {transformation: [-1f,0f,0f,-0.075f,0f,0f,1f,-0.9375f,0f,1f,0f,0.2488f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_magazine) {transformation: [-1f,0f,0f,-0.1844f,0f,0f,1f,-0.7405f,0f,1f,0f,0.1962f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_grip) {transformation: [-1f,0f,0f,-0.1844f,0f,0f,1f,-0.7405f,0f,1f,0f,0.1962f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_trigger) {transformation: [-1f,0f,0f,-0.1844f,0f,0f,1f,-0.7712f,0f,1f,0f,0.2006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_trigger_gaurd) {transformation: [-1f,0f,0f,-0.1844f,0f,0f,1f,-0.8036f,0f,1f,0f,0.2295f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-1f,0f,0f,-0.2188f,0f,1f,0f,-0.4125f,0f,0f,-1f,0.175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_magazine1) {transformation: [-1f,0f,0f,0.1719f,0f,-0.3827f,0.9239f,-0.7975f,0f,0.9239f,0.3827f,0.2905f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-1f,0f,0f,0.1719f,0f,1f,0f,-0.4125f,0f,0f,-1f,0.175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"barrel1":{"px":-0.20625000000000002,"py":-1.1,"pz":0.2750000000000001,"ry":0,"rx":90}}}