# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.akm.node.magazine] at @s run function animated_java:akm/variants/default/zzz/apply_to_node_magazine
execute on passengers if entity @s[tag=aj.akm.node.chamber] at @s run function animated_java:akm/variants/default/zzz/apply_to_node_chamber
execute on passengers if entity @s[tag=aj.akm.node.akm1] at @s run function animated_java:akm/variants/default/zzz/apply_to_node_akm1
execute on passengers if entity @s[tag=aj.akm.node.right_arm] at @s run function animated_java:akm/variants/default/zzz/apply_to_node_right_arm
execute on passengers if entity @s[tag=aj.akm.node.left_arm] at @s run function animated_java:akm/variants/default/zzz/apply_to_node_left_arm
return 1