# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^0.1375 ^-1.47978125 ^0.0901425 ~0 ~90
data modify entity @s data.locators.akm2 merge value { px: 0.1375, py: -1.47978125, pz: 0.0901425, ry: 0, rx: 90 }