# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^-0.20625 ^-1.94853125 ^0.3713925 ~0 ~90
data modify entity @s data.locators.akm merge value { px: -0.20625, py: -1.94853125, pz: 0.3713925, ry: 0, rx: 90 }