# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^-0.2375 ^-1.41728125 ^-0.0973575 ~0 ~90
data modify entity @s data.locators.akm merge value { px: -0.2375, py: -1.41728125, pz: -0.0973575, ry: 0, rx: 90 }