# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args.export_namespace set from entity @s data.export_namespace
data modify entity @s data.rig_hash set value 'fd8e4c3b148662178c8eeb08e2732cd80cef61afd683911189d7c885c0ce939a'