# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args.export_namespace set from entity @s data.export_namespace
data modify entity @s data.rig_hash set value 'cdf73948f245b5356addd91effa6184acc711906b3e9ecc38411bdaf959afaa3'