# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args.export_namespace set from entity @s data.export_namespace
data modify entity @s data.rig_hash set value '144133cc9900aea0147df271f8891f11caf7d9a4b3498c6fd148da98550ed999'