# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(magazine) ~ ~ ~ ~ ~
$execute as $(magazine) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(chamber) ~ ~ ~ ~ ~
$execute as $(chamber) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(akm1) ~ ~ ~ ~ ~
$execute as $(akm1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(right_arm) ~ ~ ~ ~ ~
$execute as $(right_arm) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(magazine2) ~ ~ ~ ~ ~
$execute as $(magazine2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(forearm) ~ ~ ~ ~ ~
$execute as $(forearm) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1