# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:player rig_hash set value '9b9d36416590173d44bea41733565aa7e8bf54ac05b8c5562b7db9024072d233'
scoreboard objectives add aj.wakeup.frame dummy
scoreboard objectives add aj.s1.frame dummy