# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.chrome_shotgun.root] run return 0
execute if entity @s[tag=aj.chrome_shotgun.animation.equip.playing] run function animated_java:chrome_shotgun/animations/equip/zzz/on_tick
execute if entity @s[tag=aj.chrome_shotgun.animation.shoot.playing] run function animated_java:chrome_shotgun/animations/shoot/zzz/on_tick
execute if entity @s[tag=aj.chrome_shotgun.animation.load_start.playing] run function animated_java:chrome_shotgun/animations/load_start/zzz/on_tick
execute if entity @s[tag=aj.chrome_shotgun.animation.new.playing] run function animated_java:chrome_shotgun/animations/new/zzz/on_tick
execute on passengers run rotate @s ~ ~