# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @p remove deadism.weapon.cooldown
function animated_java:glock/animations/reload_empty/play