# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(magazine) { transformation: [-1f,0f,0f,-0.2062f,0f,0f,1f,-0.8131f,0f,1f,0f,0.263f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(chamber) { transformation: [-1f,0f,0f,-0.2062f,0f,0f,1f,-1.0006f,0f,1f,0f,0.3021f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(akm1) { transformation: [-1f,0f,0f,-0.2062f,0f,0f,1f,-1.0006f,0f,1f,0f,0.3021f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(right_arm) { transformation: [-1f,0f,0f,-0.2188f,0f,1f,0f,-0.4062f,0f,0f,-1f,0.2188f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(magazine2) { transformation: [-1f,0f,0f,0.1375f,0f,-0.4848f,0.8746f,-0.7521f,0f,0.8746f,0.4848f,0.2771f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(forearm) { transformation: [-1f,0f,0f,0.1687f,0f,1f,0f,-0.4375f,0f,0f,-1f,0.2188f,0f,0f,0f,1f], start_interpolation: 0 }