# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.fire_extinguisher.root] run return 0
execute if entity @s[tag=aj.fire_extinguisher.animation.equip.playing] run function animated_java:fire_extinguisher/animations/equip/zzz/on_tick
execute if entity @s[tag=aj.fire_extinguisher.animation.hit.playing] run function animated_java:fire_extinguisher/animations/hit/zzz/on_tick
execute on passengers run rotate @s ~ ~