# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.glock.root] run return 0
execute if entity @s[tag=aj.glock.animation.equip.playing] run function animated_java:glock/animations/equip/zzz/on_tick
execute if entity @s[tag=aj.glock.animation.shoot.playing] run function animated_java:glock/animations/shoot/zzz/on_tick
execute if entity @s[tag=aj.glock.animation.shoot_final.playing] run function animated_java:glock/animations/shoot_final/zzz/on_tick
execute if entity @s[tag=aj.glock.animation.reload_mid.playing] run function animated_java:glock/animations/reload_mid/zzz/on_tick
execute if entity @s[tag=aj.glock.animation.reload_empty.playing] run function animated_java:glock/animations/reload_empty/zzz/on_tick
execute if entity @s[tag=aj.glock.animation.sprint.playing] run function animated_java:glock/animations/sprint/zzz/on_tick
execute if entity @s[tag=aj.glock.animation.use.playing] run function animated_java:glock/animations/use/zzz/on_tick
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:glock/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~