# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shotgun_shell) {transformation: [-1f,0f,0f,-0.2812f,0f,0f,1f,-1.2125f,0f,1f,0f,-0.2437f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_clock) {transformation: [-1f,0f,0f,-0.1875f,0f,0f,1f,-2.0312f,0f,1f,0f,-0.4687f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_barrel) {transformation: [-1f,0f,0f,-0.1875f,0f,0f,1f,-1.5625f,0f,1f,0f,-0.4062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_trigger) {transformation: [-1f,0f,0f,-0.25f,0f,0f,1f,-1.211f,0f,1f,0f,-0.4394f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_trigger_part) {transformation: [-1f,0f,0f,-0.25f,0f,0f,1f,-1.25f,0f,1f,0f,-0.4562f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_chrome_shotgun) {transformation: [-1.0243f,0f,0f,-0.2187f,0f,0f,1.0243f,-1.2812f,0f,1.0243f,0f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-0.9914f,-0.1305f,0f,-0.4062f,-0.1305f,0.9914f,0f,-0.4687f,0f,0f,-1f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-1.0208f,0f,0f,0.375f,0f,1.0208f,0f,-0.4687f,0f,0f,-1.0208f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}