# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shotgun_shell) {transformation: [-1f,0f,0f,-0.2812f,0f,0f,1f,-1.3688f,0f,1f,0f,0.0375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_clock) {transformation: [-1f,0f,0f,-0.1875f,0f,0f,1f,-2.1875f,0f,1f,0f,-0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_barrel) {transformation: [-1f,0f,0f,-0.1875f,0f,0f,1f,-1.7187f,0f,1f,0f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_trigger) {transformation: [-1f,0f,0f,-0.25f,0f,0f,1f,-1.3673f,0f,1f,0f,-0.1581f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_trigger_part) {transformation: [-1f,0f,0f,-0.25f,0f,0f,1f,-1.4062f,0f,1f,0f,-0.175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_chrome_shotgun) {transformation: [-1.0243f,0f,0f,-0.2187f,0f,0f,1.0243f,-1.4375f,0f,1.0243f,0f,-0.0938f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-0.9914f,-0.1305f,0f,-0.4063f,-0.1305f,0.9914f,0f,-0.625f,0f,0f,-1f,-0.1563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-1f,0f,0f,0.375f,0f,1f,0f,-0.625f,0f,0f,-1f,-0.1562f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}