# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(shotgun_shell) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(clock) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(barrel1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(trigger) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(trigger_part) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(chrome_shotgun) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(shotgun_shell1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(right_arm) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(left_arm) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i