# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s add deadism.new
tag @s add deadism.ZOMBIE.model
function animated_java:zombie/animations/idle1/play