# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:glock/root/on_tick/select_locator_barrel1 with entity @s data.locators.barrel1
function animated_java:glock/root/on_tick/select_locator_ammo_display with entity @s data.locators.ammo_display