# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove deadism.ZOMBIE.attackAnimationPlaying
function animated_java:zombie/animations/walk1/tween {'to_frame':0, 'duration':5}