# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:zombie rig_hash set value '4b6ea4b058b2290483614681dd21fc3c6b807db3da21a1319d8ba19e08a0a7b7'
scoreboard objectives add aj.idle1.frame dummy
scoreboard objectives add aj.walk1.frame dummy
scoreboard objectives add aj.hit1.frame dummy
scoreboard objectives add aj.death1.frame dummy
scoreboard objectives add aj.stun1.frame dummy
scoreboard objectives add aj.bullet_eat_1.frame dummy
scoreboard objectives add aj.bullet_eat_2.frame dummy