# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:chrome_shotgun/animations/reload_load1/play
execute on vehicle run tag @s remove deadism.weapon.cooldown