# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @p remove deadism.IsSprinting
tag @p remove deadism.weapon.cooldown
function animated_java:glock/animations/idle_still/tween {to_frame: 0, duration: 1}