# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:chrome_shotgun rig_hash set value 'b08e09a1b9f95d43d3dabf89b5f40ec8e0be193bb54b087587a6fd53ce263398'
scoreboard objectives add aj.equip.frame dummy
scoreboard objectives add aj.shoot.frame dummy
scoreboard objectives add aj.reload_start.frame dummy
scoreboard objectives add aj.reload_load1.frame dummy
scoreboard objectives add aj.reload_end.frame dummy
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.run.frame dummy