# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:chrome_shotgun rig_hash set value 'cdf73948f245b5356addd91effa6184acc711906b3e9ecc38411bdaf959afaa3'
scoreboard objectives add aj.equip.frame dummy
scoreboard objectives add aj.shoot.frame dummy
scoreboard objectives add aj.reload_start.frame dummy
scoreboard objectives add aj.reload_load1.frame dummy
scoreboard objectives add aj.reload_end.frame dummy