# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:chrome_shotgun rig_hash set value 'eebad73b89ca80ac70308effd88aad14f273a34a278bfe8cd7821cee447aa366'
scoreboard objectives add aj.equip.frame dummy
scoreboard objectives add aj.shoot.frame dummy
scoreboard objectives add aj.reload_start.frame dummy
scoreboard objectives add aj.reload_load1.frame dummy
scoreboard objectives add aj.reload_end.frame dummy
scoreboard objectives add aj.run.frame dummy
scoreboard objectives add aj.wall.frame dummy