# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:zombie/animations/idle1/zzz/apply_frame {frame: 100}
scoreboard players add @s aj.idle1.frame 1