# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers run function animated_java:chrome_shotgun/animations/run/zzz/frames/$(frame) with entity @s data.uuids_by_name
execute on passengers run function animated_java:chrome_shotgun/animations/run/zzz/zzz/1 with entity @s data.uuids_by_name
return 1