# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify entity $(muzzleflash) interpolation_duration set value 1
$data modify entity $(slide) interpolation_duration set value 1
$data modify entity $(barrel) interpolation_duration set value 1
$data modify entity $(magazine) interpolation_duration set value 1
$data modify entity $(grip) interpolation_duration set value 1
$data modify entity $(trigger) interpolation_duration set value 1
$data modify entity $(trigger_gaurd) interpolation_duration set value 1
$data modify entity $(right_arm) interpolation_duration set value 1
$data modify entity $(magazine1) interpolation_duration set value 1
$data modify entity $(left_arm) interpolation_duration set value 1