# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_magazine) {transformation: [0f,0.766f,-0.6428f,0.0767f,0f,0.6428f,0.766f,-0.877f,1f,0f,0f,0.2063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_chamber) {transformation: [0f,0.766f,-0.6428f,0.2271f,0f,0.6428f,0.766f,-0.9955f,1f,0f,0f,0.2063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_akm1) {transformation: [0f,0.766f,-0.6428f,0.2271f,0f,0.6428f,0.766f,-0.9955f,1f,0f,0f,0.2063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_right_arm) {transformation: [0f,-0.6428f,-0.766f,-0.2188f,0f,0.766f,-0.6428f,-0.5937f,1f,0f,0f,0.2188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_magazine2) {transformation: [0f,0f,0f,0.1687f,0f,0f,0f,-0.4375f,0f,0f,0f,0.2188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
$data merge entity $(bone_forearm) {transformation: [0f,0f,0f,0.1687f,0f,0f,0f,-0.4375f,0f,0f,0f,0.2188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 2}
data modify entity @s data merge value {"cameras":{},"locators":{"akm":{"px":0.5642946361726233,"py":-1.3380930536681972,"pz":0.20625000000000004,"ry":270,"rx":50}}}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:akm/animations/equip/zzz/frames/0_root_function