# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_magazine) {transformation: [0f,0.766f,-0.6428f,-0.1733f,0f,0.6428f,0.766f,-0.6895f,1f,0f,0f,0.3f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_chamber) {transformation: [0f,0.766f,-0.6428f,-0.0229f,0f,0.6428f,0.766f,-0.808f,1f,0f,0f,0.3f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_akm1) {transformation: [0f,0.766f,-0.6428f,-0.0229f,0f,0.6428f,0.766f,-0.808f,1f,0f,0f,0.3f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_magazine2) {transformation: [0f,0f,0f,-0.2017f,0f,0f,0f,-0.6337f,0f,0f,0f,0.3f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [0f,-0.6428f,-0.766f,-0.4688f,0f,0.766f,-0.6428f,-0.4062f,1f,0f,0f,0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_forearm) {transformation: [-0.3073f,0.4756f,-0.8242f,-0.2814f,-0.18f,0.8214f,0.5411f,-0.7137f,0.9344f,0.3146f,-0.1668f,0.1681f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_magazine1) {transformation: [0f,0f,0f,-0.4806f,0f,0f,0f,-1.2214f,0f,0f,0f,0.0048f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_chamber1) {transformation: [0f,0f,0f,-0.4806f,0f,0f,0f,-1.2214f,0f,0f,0f,0.0048f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_akm3) {transformation: [0f,0f,0f,-0.4806f,0f,0f,0f,-1.2214f,0f,0f,0f,0.0048f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_muzzleflash) {transformation: [0f,0f,0f,-0.2031f,0f,0f,0f,-0.7703f,0f,0f,0f,0.4f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"akm":{"px":0.31429463617262315,"py":-1.1505930536681972,"pz":0.3,"ry":270,"rx":50},"akm2":{"px":-0.4806071831471685,"py":-1.2213633906949368,"pz":0.004811239180543514,"ry":123.48560936631657,"rx":55.230178956391}}}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:akm/animations/equip/zzz/frames/0_root_function