# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute rotated as @p positioned ^ ^ ^1 run playsound minecraft:item.mace.smash_ground master @a ~ ~ ~ 1 0.8 1
execute as @p at @s anchored eyes positioned ^ ^ ^ run function deadism:zprivate/weapons/melee/fire_extinguisher/damage