# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$kill $(magazine)
$kill $(chamber)
$kill $(akm1)
$kill $(right_arm)
$kill $(magazine2)
$kill $(forearm)