# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 on passengers run data modify entity @s interpolation_duration set value 2
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.wall.frame
function animated_java:akm/animations/wall/zzz/apply_frame with storage animated_java:temp args
execute if score @s aj.wall.frame matches 1.. run return run function animated_java:akm/animations/wall/pause
scoreboard players add @s aj.wall.frame 1