# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.elevator_door.root] run return 0
execute if entity @s[tag=aj.elevator_door.animation.open.playing] run function animated_java:elevator_door/animations/open/zzz/on_tick
execute if entity @s[tag=aj.elevator_door.animation.close.playing] run function animated_java:elevator_door/animations/close/zzz/on_tick
execute on passengers run rotate @s ~ ~