# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(shotgun_shell) ~ ~ ~ ~ ~
$execute as $(shotgun_shell) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(clock) ~ ~ ~ ~ ~
$execute as $(clock) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(barrel1) ~ ~ ~ ~ ~
$execute as $(barrel1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(trigger) ~ ~ ~ ~ ~
$execute as $(trigger) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(trigger_part) ~ ~ ~ ~ ~
$execute as $(trigger_part) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(chrome_shotgun) ~ ~ ~ ~ ~
$execute as $(chrome_shotgun) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(shotgun_shell1) ~ ~ ~ ~ ~
$execute as $(shotgun_shell1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(right_arm) ~ ~ ~ ~ ~
$execute as $(right_arm) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(left_arm) ~ ~ ~ ~ ~
$execute as $(left_arm) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1