# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @p remove deadism.weapon.cooldown
tag @p remove deadism.weapon.reloading
execute as @p at @s run function deadism:zprivate/weapons/pistols/glock/reload_end
tag @p remove deadism.IsSprinting