# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(muzzleflash) run function animated_java:glock/variants/police/zzz/apply_to_node_muzzleflash
$execute as $(slide) run function animated_java:glock/variants/police/zzz/apply_to_node_slide
$execute as $(barrel) run function animated_java:glock/variants/police/zzz/apply_to_node_barrel
$execute as $(magazine) run function animated_java:glock/variants/police/zzz/apply_to_node_magazine
$execute as $(grip) run function animated_java:glock/variants/police/zzz/apply_to_node_grip
$execute as $(trigger) run function animated_java:glock/variants/police/zzz/apply_to_node_trigger
$execute as $(trigger_gaurd) run function animated_java:glock/variants/police/zzz/apply_to_node_trigger_gaurd
$execute as $(right_arm) run function animated_java:glock/variants/police/zzz/apply_to_node_right_arm
$execute as $(magazine1) run function animated_java:glock/variants/police/zzz/apply_to_node_magazine1
$execute as $(left_arm) run function animated_java:glock/variants/police/zzz/apply_to_node_left_arm