# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:akm/zzz/reset_floating_entities
execute on passengers if entity @s[tag=aj.akm.node.magazine] run data merge entity @s { transformation: [-1f,0f,0f,-0.2062f,0f,0f,1f,-0.8756f,0f,1f,0f,-0.0808f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.akm.node.chamber] run data merge entity @s { transformation: [-1f,0f,0f,-0.2062f,0f,0f,1f,-1.0631f,0f,1f,0f,-0.0417f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.akm.node.akm1] run data merge entity @s { transformation: [-1f,0f,0f,-0.2062f,0f,0f,1f,-1.0631f,0f,1f,0f,-0.0417f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.akm.node.right_arm] run data merge entity @s { transformation: [-1f,0f,0f,-0.2187f,0f,1f,0f,-0.4687f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.akm.node.left_arm] run data merge entity @s { transformation: [-1f,0f,0f,0.1719f,0f,1f,0f,-0.4687f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: 0 }