# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:akm rig_hash set value 'b5bdde538d1680fcf680c0929ac6e9d743fbd7b6a546a8dfacbe0d99649adce7'
scoreboard objectives add aj.equip.frame dummy
scoreboard objectives add aj.shoot.frame dummy
scoreboard objectives add aj.reload.frame dummy