# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:elevator_door rig_hash set value '34c493bb4f32a073c6eca2e17c1b89dab647867fbf7b8fceacc2d858ebc83ed4'
scoreboard objectives add aj.open.frame dummy
scoreboard objectives add aj.close.frame dummy