# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_shotgun_shell) {transformation: [0f,0f,0f,-0.1661f,0f,0f,0f,-0.6124f,0f,0f,0f,0.5969f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_clock) {transformation: [-0.9962f,0.0872f,0f,-0.1728f,0.0872f,0.9962f,0f,-0.7248f,0f,0f,-1f,0.9063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_barrel1) {transformation: [-0.9962f,0.0872f,0f,-0.1701f,0.0872f,0.9962f,0f,-0.6937f,0f,0f,-1f,0.6719f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_trigger) {transformation: [-0.9962f,0.0872f,0f,-0.2027f,0.0872f,0.9962f,0f,-0.7074f,0f,0f,-1f,0.4961f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_trigger_part) {transformation: [-0.9962f,0.0872f,0f,-0.2034f,0.0872f,0.9962f,0f,-0.7158f,0f,0f,-1f,0.5156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_chrome_shotgun) {transformation: [-0.9962f,0.0872f,0f,-0.1843f,0.0872f,0.9962f,0f,-0.6767f,0f,0f,-1f,0.5313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shotgun_shell1) {transformation: [0f,0f,0f,-0.1724f,0f,0f,0f,-0.6882f,0f,0f,0f,0.5186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-0.9877f,-0.1175f,-0.1034f,-0.2777f,0.0864f,0.1413f,-0.9862f,-0.6686f,0.1305f,-0.983f,-0.1294f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-0.8827f,0.4434f,-0.1556f,-0.0293f,0.2013f,0.0576f,-0.9778f,-0.7342f,-0.4246f,-0.8945f,-0.1401f,0.7375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"barrel":{"px":-0.1968702838013368,"py":-0.6411184466138399,"pz":1.1875,"ry":0,"rx":3.10536311491268e-17}}}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:chrome_shotgun/animations/reload_end/zzz/frames/20_root_function