# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^-0.0875 ^-0.88125 ^0.44375 ~0 ~90
data modify entity @s data.locators.ammo_display merge value { px: -0.0875, py: -0.88125, pz: 0.44375, ry: 0, rx: 90 }