# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^-0.33125 ^-1.06875 ^0.275 ~0 ~90
data modify entity @s data.locators.barrel1 merge value { px: -0.33125, py: -1.06875, pz: 0.275, ry: 0, rx: 90 }