# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify entity $(magazine) interpolation_duration set value 2
$data modify entity $(chamber) interpolation_duration set value 2
$data modify entity $(akm1) interpolation_duration set value 2
$data modify entity $(right_arm) interpolation_duration set value 2
$data modify entity $(magazine2) interpolation_duration set value 2
$data modify entity $(forearm) interpolation_duration set value 2