# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify entity $(magazine) start_interpolation set value -1
$data modify entity $(chamber) start_interpolation set value -1
$data modify entity $(akm1) start_interpolation set value -1
$data modify entity $(right_arm) start_interpolation set value -1
$data modify entity $(magazine2) start_interpolation set value -1
$data modify entity $(forearm) start_interpolation set value -1